### PR TITLE
feat [1/4]: add protobuf protos to test tools

### PR DESCRIPTION
**Pull request by xiaozhenliu-gg5**
Use `api-common-protos` and `protobuf` submodules to provide dependencies for annotations like `method_signature`.

### CODE REVIEW

**Comment by software-dov** [comment]
Just to be clear, these protos are added as a submodule, correct?

**Comment by xiaozhenliu-gg5** [comment]
Yes, the `protobuf` is added as submodule so that we can directly use them as one `--proto_path` in protoc command, then we can find the annotations like `method_signature`. @software-dov (removed the explicit proto files in `test/tools/protos` and use the submodule instead)

Also for the branch protection ([screenshot](https://screenshot.googleplex.com/BsHKv9zn4uKtqLr)) Seems I cannot merge the PR before getting an approval. Thanks!

**Review by software-dov — APPROVED** [review]

**Comment by software-dov** [comment]
It looks like the branch protection is set up now. Thanks for doing that! I know @JustinBeckwith is encouraging all repos to have it enabled.

**Comment by xiaozhenliu-gg5** [comment]
Got it, thanks for confirmation! @software-dov

**Pull request merged**
